# Generated by Django 3.1.7 on 2021-03-21 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_location', models.TextField()),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.category')),
            ],
        ),
    ]
