# Generated by Django 3.1.7 on 2021-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_is_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
